### ISSUE TITLE
easydict

### ISSUE THREAD

**Issue by skachm** [Austriker/py-faster-rcnn#5]
Getting an odd error trying to run demo.py:

```
$ ./tools/demo.py
Traceback (most recent call last):
  File "./tools/demo.py", line 17, in <module>
    from fast_rcnn.config import cfg
  File "/home/skachm/detection/py-faster-rcnn-austriker/tools/../lib/fast_rcnn/config.py", line 5, in <module>
    from easydict import EasyDict as edict
ImportError: No module named 'easydict'
```

easydict is installed though:

```
$ sudo pip install easydict
Requirement already satisfied (use --upgrade to upgrade): easydict in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

Plus I can run that line successfully in the python shell and by calling config.py without any errors.

Using python 2.7.6 on Ubuntu 14.04 server

**Comment by skachm** [comment]
This seems to be caused by the python version because demo.py calls python3

**Comment by Austriker** [comment]
Hi @skachm, I only tested the code with python 3. Thank you for the feedback.
